name: Check HTML

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Vérifier que le fichier index.html existe
      run: |
        if [ -f index.html ]; then
          echo "Super ! Le fichier index.html existe bien."
        else
          echo "Erreur : Le fichier index.html est introuvable à la racine du dépôt !"
          exit 1
        fi