name: Check HTML

on: [push, pull_request]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # On anticipe la mise à jour de GitHub

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'  # On passe en version 24 !

    - name: Run HTMLHint
      run: |
        npm install -g htmlhint
        htmlhint *.html